version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.14.2
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: go.opentelemetry.io/otel/trace
    versions:
    - 0.18.0
    - 0.19.0
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
  - dependency-name: go.opencensus.io
    versions:
    - 0.22.6
    - 0.23.0
  - dependency-name: go.opentelemetry.io/otel
    versions:
    - 0.16.0
    - 0.17.0
